future4code/Vaughan-labe-ninja4

src/constants/labeninjasAPI.js

arrumei a constante key

---

src/components/CardCadastro.js

card cadastro (quase) estilizado

---

src/App.js
src/components/CardProdutos.js
src/pages/PaginaListagem.js

Feito CardProdutos

---

src/components/CardProdutos.js

removing trash

---

src/App.js
src/components/CardCarrinho.js
src/pages/PaginaCarrinho.js

fiz esqueleto do carrinho

---

package-lock.json
package.json
src/App.js
src/constants/Tema.js

adicionado mui

---

src/App.js
src/components/CardCadastro.js

não sei o que não tá funcionando, não aparece nem o erro e nem a reponse

---

package-lock.json
package.json
src/App.js
src/components/CardProdutos.js
src/pages/PaginaCadastro.js
src/pages/PaginaDetalhes.js
src/pages/PaginaListagem.js

Gabriel martins

---

src/App.js
src/components/CardCarrinho.js
src/components/CardProdutos.js
src/pages/PaginaCarrinho.js

produtos estao indo pro carrinho

---

src/App.js
src/components/CardCarrinho.js
src/components/CardProdutos.js
src/pages/PaginaCarrinho.js

produtos tao indo pro carrinho

---

src/App.js
src/components/CardCarrinho.js
src/components/CardProdutos.js
src/components/Header.js
src/pages/PaginaCarrinho.js

Gabriela carrinho

---

src/components/CardProdutos.js

arrumado bugs CardProdutos

---

src/components/CardCadastro.js

criação de jobs criado com sucesso

---

src/App.js
src/components/CardProdutos.js
src/components/Header.js
src/pages/PaginaCarrinho.js
src/pages/PaginaDetalhes.js

carrinho no detalhes funcionando, comecei renderizacao no app

---

src/App.js
src/components/CardCadastro.js

tentativa de estilizar o cadastro (devolvam meu CSS pelamordedeus)

---

src/App.js
src/components/CardProdutos.js
src/pages/PaginaDetalhes.js

Modificacao proposta

---

src/App.js
src/components/CardProdutos.js
src/pages/PaginaDetalhes.js

arrumei carrinho

---

src/App.js
src/components/CardCarrinho.js
src/components/CardProdutos.js
src/constants/Tema.js
src/pages/PaginaCarrinho.js

feita estilização do carrinho

---

src/pages/PaginaDetalhes.js

Responsividade detalhes

---

src/components/CardProdutos.js

resposividade dos inputs

---

src/App.js
src/components/CardCarrinho.js
src/pages/PaginaCarrinho.js

estilizacao carrinho

---

src/App.js
src/components/CardCarrinho.js
src/pages/PaginaCarrinho.js
src/pages/PaginaDetalhes.js

botao de voltar do carrinho debugado

---

src/components/CardCadastro.js

checkbox e estilização do card de cadastro

---

src/components/Header.js
src/components/Home.js
src/pages/PaginaDetalhes.js

Responsidade

---

src/components/Header.js

responsividade carrinho

---

src/components/Header.js
src/constants/Tema.js

icone header diminuido

---

src/components/CardProdutos.js
src/pages/PaginaDetalhes.js

delete job feito

---

README.md
src/App.js
src/components/CardCadastro.js
src/components/CardCarrinho.js
src/components/CardProdutos.js
src/components/Header.js
src/components/Home.js
src/components/styled-cardcadastro.js
src/components/styled-cardcarrinho.js
src/components/styled-cardprodutos.js
src/components/styled-header.js
src/components/styled-home.js
src/constants/Tema.js
src/pages/PaginaCarrinho.js
src/pages/PaginaDetalhes.js
src/pages/styled-paginacarrinho.js
src/pages/styled-paginadetalhes.js
src/styled-app.js

feito readme e algumas manutencoes na estilizacao
